---
- name: Update all systems
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update package cache and upgrade all packages (Debian/Ubuntu)
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"
      register: apt_result

    - name: Update packages (RHEL/CentOS/Rocky/AlmaLinux)
      yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"
      register: yum_result

    - name: Update packages (Fedora)
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution == "Fedora"
      register: dnf_result

    - name: Update packages (Arch Linux)
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Archlinux"
      register: pacman_result

    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: Display update results
      debug:
        msg: |
          System: {{ inventory_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Updates completed: {{ ansible_date_time.iso8601 }}
          {% if ansible_os_family == "Debian" and reboot_required_file.stat.exists %}
          ⚠️  REBOOT REQUIRED
          {% endif %}

    - name: Create update log
      lineinfile:
        path: /var/log/ansible-updates.log
        line: "{{ ansible_date_time.iso8601 }} - Updates completed on {{ inventory_hostname }}"
        create: yes
        mode: '0644'
      ignore_errors: yes